2019-12-12 22:34:36,866 ERROR: Exception on /login [GET] [in c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\routes.py", line 72, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\templates\login.html", line 1, in <module>
    {% extends "base.html" %}
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\templates\login.html", line 14, in root
    <p>
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\templates\base.html", line 55, in root
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\templates\login.html", line 45, in block_content
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'reset_password' instead?
2019-12-12 22:36:02,205 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:45]
2019-12-12 22:36:06,138 ERROR: Exception on /login [GET] [in c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\routes.py", line 72, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\templates\login.html", line 1, in <module>
    {% extends "base.html" %}
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\templates\login.html", line 14, in root
    <p>
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\templates\base.html", line 55, in root
  File "C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\templates\login.html", line 45, in block_content
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\srira\onedrive\desktop\anvesh\wp\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'reset_password' instead?
2019-12-12 22:39:35,065 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:47]
2019-12-12 23:22:31,847 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:49]
2019-12-13 00:22:10,905 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:49]
2019-12-13 00:24:24,833 INFO: Microblog startup [in C:\Users\srira\OneDrive\Desktop\Anvesh\WP\microblog\app\__init__.py:49]
